<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>52846772-72d1-4288-810f-495c750fddbd</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="GeographicLib.NET" Version="2.3.2" />
      <PackageReference Include="GovUk.Frontend.AspNetCore" Version="3.2.3" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\css\site.css" />
      <_ContentIncludedByDefault Remove="wwwroot\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\js\site.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\LICENSE.md" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\department-for-education_black.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\department-for-education_white.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\dfe-logo-alt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\dfe-logo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\bold-affa96571d-v2.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\bold-b542beb274-v2.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\light-94a07e06a1-v2.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\light-f591b13f7d-v2.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\department-for-education_black.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\department-for-education_white.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\favicon.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-crest.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-icon-180.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-icon-192.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-icon-512.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-icon-mask.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-logotype-crown.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\govuk-opengraph-image.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-alert-information.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-alert-success.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-alert-warning.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-arrow-black-down.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-arrow-black-up.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-arrow-white-down.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-arrow-white-up.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-close-cross-black.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-document.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-document.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-progress-tick.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-progress-tick.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-search-black.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-search-blue.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-search-white.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-tag-remove-cross-white.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-tag-remove-cross.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-toggle-plus-minus.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-wysiwyg-bold.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-wysiwyg-italic.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-wysiwyg-ordered-list.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-wysiwyg-underline.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\icon-wysiwyg-unordered-list.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-apple-touch-icon-152x152-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-apple-touch-icon-167x167-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-apple-touch-icon-180x180-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-apple-touch-icon-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-logotype-crest-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-logotype-crest-2024.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\images\moj-opengraph-image-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\manifest.json" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\favicon.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-crest.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-icon-180.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-icon-192.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-icon-512.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-icon-mask.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\images\govuk-opengraph-image.png" />
      <_ContentIncludedByDefault Remove="wwwroot\assets\rebrand\manifest.json" />
      <_ContentIncludedByDefault Remove="wwwroot\css\application.css" />
      <_ContentIncludedByDefault Remove="wwwroot\images\department-for-education_black.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\department-for-education_white.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\images\favicon.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-crest.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-icon-180.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-icon-192.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-icon-512.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-icon-mask.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-logotype-crown.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\govuk-opengraph-image.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-alert-information.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-alert-success.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-alert-warning.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-arrow-black-down.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-arrow-black-up.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-arrow-white-down.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-arrow-white-up.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-close-cross-black.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-document.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-document.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-progress-tick.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-progress-tick.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-search-black.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-search-blue.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-search-white.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-tag-remove-cross-white.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-tag-remove-cross.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-toggle-plus-minus.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-wysiwyg-bold.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-wysiwyg-italic.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-wysiwyg-ordered-list.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-wysiwyg-underline.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\icon-wysiwyg-unordered-list.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-apple-touch-icon-152x152-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-apple-touch-icon-167x167-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-apple-touch-icon-180x180-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-apple-touch-icon-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-logotype-crest-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-logotype-crest-2024.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\moj-opengraph-image-2024.png" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\favicon.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-crest.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-icon-180.png" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-icon-192.png" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-icon-512.png" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-icon-mask.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\images\govuk-opengraph-image.png" />
      <_ContentIncludedByDefault Remove="wwwroot\rebrand\manifest.json" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dfefrontend-2.0.0.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\moj-frontend.min.js" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove=".gitignore" />
    </ItemGroup>

</Project>
